### ISSUE TITLE
"Gulp" frameworks

### ISSUE THREAD

**Issue by apollo7321** [SStalker/EVOS#4]
Download the used frameworks like jQuery (js and css files) to the resources folder. Afterwards run gulp over the files. Then remove current includes for js and css (the CDN included stuff) and add hour "gulped" file.

**Comment by lhannigbrinck** [comment]
@cwansart , @lkschenk : Got some problems with MathJax here. A fresh copy of MathJax (unwraped and without configuration) has a size of about 70MB and multiply files which load dynamically. I've read a little into it and it seems like it is possible to [reduce the size](https://github.com/mathjax/MathJax-docs/wiki/Guide%3A-reducing-size-of-a-mathjax-installation) if you strip down functionallity. There also is a "[mathjax-node](https://github.com/mathjax/MathJax-node)" and an experimental [single file version](https://github.com/pkra/MathJax-single-file) here on github. 
Since I don't really know which functionality is needed. Could one of you probably look further into it?

**Comment by apollo7321** [comment]
Just take this (60 KB) https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML

**Comment by lhannigbrinck** [comment]
@cwansart The problem still are the files which are dynamical loaded from the CDN in the example code from @lkschenk . As you can see [here](https://netcase.hs-osnabrueck.de/index.php/s/FtfkhxZNzNHnXhH) there are multiple files which are loaded when they are needed by Mathjax.On the left side of the linked picture you can see the original example, on the right side you can see a version with the above linked file localy included. It looks like this might be a little more complex to include than e.g. jquery

**Comment by apollo7321** [comment]
OK, then skip that. We'll include it addionatly. We can search for a solution later on. Thanks for checking.

**Comment by lhannigbrinck** [comment]
Ok.
@cwansart for further information about the problem with MathJax and browserify you could read [this link](https://github.com/mathjax/MathJax/issues/951). An open issue from the MathJax github repository.
